config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :semillas
  root to: 'application#bienvenidxs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grupo.rb
class Grupo < ApplicationRecord
end

app/models/huertum.rb
class Huertum < ApplicationRecord
end

app/models/semilla.rb
class Semilla < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def bienvenidxs
    end
end

app/controllers/semillas_controller.rb
class SemillasController < ApplicationController
  before_action :set_semilla, only: [:show, :edit, :update, :destroy]

  # GET /semillas
  # GET /semillas.json
  def index
    @semillas = Semilla.all
  end

  # GET /semillas/1
  # GET /semillas/1.json
  def show
  end

  # GET /semillas/new
  def new
    @semilla = Semilla.new
  end

  # GET /semillas/1/edit
  def edit
  end

  # POST /semillas
  # POST /semillas.json
  def create
    @semilla = Semilla.new(semilla_params)

    respond_to do |format|
      if @semilla.save
        format.html { redirect_to @semilla, notice: 'Semilla was successfully created.' }
        format.json { render :show, status: :created, location: @semilla }
      else
        format.html { render :new }
        format.json { render json: @semilla.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /semillas/1
  # PATCH/PUT /semillas/1.json
  def update
    respond_to do |format|
      if @semilla.update(semilla_params)
        format.html { redirect_to @semilla, notice: 'Semilla was successfully updated.' }
        format.json { render :show, status: :ok, location: @semilla }
      else
        format.html { render :edit }
        format.json { render json: @semilla.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /semillas/1
  # DELETE /semillas/1.json
  def destroy
    @semilla.destroy
    respond_to do |format|
      format.html { redirect_to semillas_url, notice: 'Semilla was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_semilla
      @semilla = Semilla.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def semilla_params
      params.require(:semilla).permit(:nombre, :tipo, :origen, :cantidad, :fecha_siembra)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Users was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Users was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_index_url, notice: 'Users was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/semillas_helper.rb
module SemillasHelper
end

app/helpers/semillass_helper.rb
module SemillassHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/bienvenidxs.html.erb
<nav>
  <ul>
    <li><%= link_to 'Iniciar sesión', new_user_session_url%></li>
    <li><%= link_to 'Registrarse', new_user_registration_url%></li>
  </ul>
</nav>
<main>
  <h1>Hola Humane!</h1>
  <h2>Esta es la pagina principal de Huertapp: Banco de semillas confederado!</h2>
  <p>Estamos intentando generar una aplicacion
que posibilite el registro de semillas disponibles para la siembra
en diferentes comunidades.</p>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Huertas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/semillas/_form.html.erb
<%= form_with(model: semilla, local: true) do |form| %>
  <% if semilla.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(semilla.errors.count, "error") %> prohibited this semilla from being saved:</h2>

      <ul>
        <% semilla.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :origen %>
    <%= form.text_field :origen %>
  </div>

  <div class="field">
    <%= form.label :cantidad %>
    <%= form.text_field :cantidad %>
  </div>

  <div class="field">
    <%= form.label :fecha_siembra %>
    <%= form.date_select :fecha_siembra %>
  </div>

  <div class="actions">
    <%= form.submit "Crear semilla" %>
  </div>
<% end %>

app/views/semillas/edit.html.erb
<h1>Editando semilla</h1>

<%= render 'form', semilla: @semilla %>

<%= link_to 'Ver semilla', @semilla %> |
<%= link_to 'Volver atrás', semillas_path %>

app/views/semillas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Semillas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tipo</th>
      <th>Origen</th>
      <th>Cantidad</th>
      <th>Fecha siembra</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @semillas.each do |semilla| %>
      <tr>
        <td><%= semilla.nombre %></td>
        <td><%= semilla.tipo %></td>
        <td><%= semilla.origen %></td>
        <td><%= semilla.cantidad %></td>
        <td><%= semilla.fecha_siembra %></td>
        <td><%= link_to 'Ver', semilla %></td>
        <td><%= link_to 'Editar', edit_semilla_path(semilla) %></td>
        <td><%= link_to 'Borrar', semilla, method: :delete, data: { confirm: '¿Segurx que querés borrar esta semilla?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Registrar semilla', new_semilla_path %>

app/views/semillas/new.html.erb
<h1>Nueva semilla</h1>

<%= render 'form', semilla: @semilla, button_name: 'Crear semilla' %>

<%= link_to 'Volver atrás', semillas_path %>

app/views/semillas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @semilla.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @semilla.tipo %>
</p>

<p>
  <strong>Origen:</strong>
  <%= @semilla.origen %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @semilla.cantidad %>
</p>

<p>
  <strong>Fecha siembra:</strong>
  <%= @semilla.fecha_siembra %>
</p>

<%= link_to 'Editar', edit_semilla_path(@semilla) %> |
<%= link_to 'Volver atrás', semillas_path %>

app/views/semillass/_form.html.erb
<%= form_with(model: semillas, local: true) do |form| %>
  <% if semillas.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(semillas.errors.count, "error") %> prohibited this semillas from being saved:</h2>

      <ul>
        <% semillas.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :origen %>
    <%= form.text_field :origen %>
  </div>

  <div class="field">
    <%= form.label :cantidad %>
    <%= form.text_field :cantidad %>
  </div>

  <div class="field">
    <%= form.label :fecha_siembra %>
    <%= form.date_select :fecha_siembra %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/semillass/edit.html.erb
<h1>Editing Semillas</h1>

<%= render 'form', semillas: @semillas %>

<%= link_to 'Show', @semillas %> |
<%= link_to 'Back', semillass_path %>

app/views/semillass/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Semillass</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tipo</th>
      <th>Origen</th>
      <th>Cantidad</th>
      <th>Fecha siembra</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @semillass.each do |semillas| %>
      <tr>
        <td><%= semillas.nombre %></td>
        <td><%= semillas.tipo %></td>
        <td><%= semillas.origen %></td>
        <td><%= semillas.cantidad %></td>
        <td><%= semillas.fecha_siembra %></td>
        <td><%= link_to 'Show', semillas %></td>
        <td><%= link_to 'Edit', edit_semillas_path(semillas) %></td>
        <td><%= link_to 'Destroy', semillas, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Semillas', new_semillas_path %>

app/views/semillass/new.html.erb
<h1>New Semillas</h1>

<%= render 'form', semillas: @semillas %>

<%= link_to 'Back', semillass_path %>

app/views/semillass/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @semillas.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @semillas.tipo %>
</p>

<p>
  <strong>Origen:</strong>
  <%= @semillas.origen %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @semillas.cantidad %>
</p>

<p>
  <strong>Fecha siembra:</strong>
  <%= @semillas.fecha_siembra %>
</p>

<%= link_to 'Edit', edit_semillas_path(@semillas) %> |
<%= link_to 'Back', semillass_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_index_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_index_path %>